services:
  redis:
    image: redis:6
    ports:
      - target: 6379
        host_ip: 127.0.0.1

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: "root"
    ports:
      - target: 5432
        host_ip: 127.0.0.1
