name: test

on:
  push:
    branches:
      - "**"

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Get dependencies
        run: go mod download

      - name: Test
        run: go test -race -covermode=atomic -cover ./...

      - name: Build
        run: go build -o app

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3

      - name: Vet
        run: go vet ./...

      - name: Staticcheck
        run: staticcheck ./...
